### ISSUE TITLE
FC value

### ISSUE THREAD

**Issue by zhangxinxinbiocc** [Center-for-Health-Data-Science/bulkDGD#1]
In the process of using bulkDGD, I encountered two issues:
1. In the file bulkDGD/analysis/dea.py, specifically in the function get_log2_fold_changes at line 687, the command is: "torch.log2((pred_means + 1e-6) / (obs_counts + 1e-6))". This command indicates that the denominator of the FC (Fold Change) is the true gene expression value, while the numerator is the predicted expression. This is opposite to the conventional way of calculating FC. 
2. Calculating |log2FC| for tutorials and recount3 BRCA expression count often results in a range of 10-30, e.g., the log2FC for EGFR is mostly less than 10. The log2FC values are smaller than the log2FC for EGFR in the article Figure 4D-F (Prada‑Luengo et al., Genome Biology).

**Comment by iprada** [comment]
Hi,

Thanks for using BulkDGD. You are now officially the first user ;)

Regarding 1.: You are right and that should be corrected. I will put a pull request together within the next days and update the code accordingly. Thanks for pointing it out and digging into the details of the software. 

Regarding 2: I need some more information. Did you follow the tutorials exactly as they are with our provided data? Both Tutorial 1 & 2? A - **minimal** - code example with the data will be helpful for me to look at it and reproduce things if needed. 

You already found my work email and you can send me the script over there. But I prefer to keep the discussion public as other users can benefit from it. More importantly, it makes my workload smaller.

Due to christmas holidays might take me some days to look at this.

best wishes, 

Iñigo Prada Luengo

**Comment by zhangxinxinbiocc** [comment]
Hi,

Thank you for your prompt response and for addressing the issues.

1） I appreciate your attention to correcting the issue, and I look forward to the updated code.

2） Thank you for providing the details. I have used the data and code from Tutorials 1 and Tutorials 2 in the bulkDGD's documentation (https://bulkdgd.readthedocs.io/en/latest/tutorial_2.html). The results align with those in the bulkDGD/tutorials/ directory of the current software version. However, in the result file bulkDGD/tutorials/tutorial_2/dea_sample_1627.csv, the |log2FC| for the majority of genes is greater than 30, including EGFR (ENSG00000146648) with a |log2FC| of 18.475014. This value of EGFR is also greater than the |log2FC| reported in the article Figure 4D-F (Prada‑Luengo et al., Genome Biology).

Best wishes,

**Comment by ValeSora** [comment]
Hi! I fixed the issue with the FC calculation (point 1) in the newest version of the code. Please let me know if it solves your problem. Sorry if it took so long!

@iprada could you help out with the second point?

**Comment by iprada** [comment]
This issue is related to issue #7. We are working on a fix.

best,

Iñigo

**Comment by ValeSora** [comment]
Hi @zhangxinxinbiocc! The issue you reported should be fixed now in the newest version of the code. Please let us know Ii you encounter any more issues.
